### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by HartLeeKonnor** [KeafyIsHere/Release-Status#1]
Mod no longer works.

**Comment by KeafyIsHere** [comment]
Hi @HartLeeKonnor I no longer play the game as much as I used to. I would ask the other person who also helps maintain this repo but I don't think he plays as much. Feel free to ask for help in VRCMG but I don't think they like this repo might be wrong but worth a shot someone might update it.

Good luck in updating this 😄

**Comment by HartLeeKonnor** [comment]
Yup
